services:
  # Backend Spring Boot
  - type: web
    name: clinica-veterinaria-backend
    env: docker
    dockerfilePath: ./apps/backend/Dockerfile
    dockerContext: . 
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: clinica-veterinaria-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: clinica-veterinaria-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: clinica-veterinaria-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: clinica-veterinaria-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: clinica-veterinaria-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
      - key: CORS_ALLOWED_ORIGINS
        value: https://clinica-veterinaria-frontend-f9us.onrender. com
      - key: SWAGGER_ENABLED
        value: true

  # Frontend React
  - type: web
    name: clinica-veterinaria-frontend
    env: static
    buildCommand: cd apps/frontend && npm ci && npm run build
    staticPublishPath: apps/frontend/dist
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://clinica-veterinaria-backend. onrender.com/api

databases:
  - name: clinica-veterinaria-db
    plan: free
    databaseName: vetclinic
    user: veterinaria