services:
  - type: web
    name: clinica-veterinaria-backend
    env: docker
    dockerfilePath: ./apps/backend/Dockerfile
    dockerContext: ./apps/backend
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      # Host/puerto/nombre desde la base de datos de Render
      - key: DB_HOST
        fromDatabase:
          name: clinica-veterinaria-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: clinica-veterinaria-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: clinica-veterinaria-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: clinica-veterinaria-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: clinica-veterinaria-db
          property: password

      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
      - key: CORS_ALLOWED_ORIGINS
        value: https://clinica-veterinaria-frontend.onrender.com
      - key: SWAGGER_ENABLED
        value: false